#!/bin/sh
ROOT_APP="$( cd "$(dirname "$0")" && cd ../../../ && pwd )";
php=$(command -v php);

echo "reloadLog";
ps aux | grep "reloadLog" | grep -v grep ||
$php $ROOT_APP/Console/cake.php printer reloadLog
sleep 1;

echo "setPrivilege";
ps aux | grep "setPrivilege" | grep -v grep ||
$php $ROOT_APP/Console/cake.php quota setPrivilege
sleep 1;

# chown www-data.www-data -R $ROOT_APP/tmp/
chmod 777 -R  $ROOT_APP/tmp/
