#!/bin/bash

function findProcess(){
	ps aux | 
	egrep print/reload_logs.service\|print/reload_print.service\|print/reload_status.service |
	grep -v grep;
}

function start(){
	findProcess || {
		/opt/print/reload_logs.service &>/dev/null &
		/opt/print/reload_print.service &>/dev/null &
		/opt/print/reload_status.service &>/dev/null &
		echo "Active: success."
	}
}

function stop(){
	process=$( 
		findProcess | 
		awk '{print "kill " $2}'
	);
	echo -e "$process";
	$process &>/dev/null &&
	echo "Stop: success.";
}

function status(){
	findProcess && 
	echo "Active: success." || 
	echo "Active: failed.";
}

case $1 in
	start)
		start
	;;
	stop)
		stop
	;;
	restart)
		stop
		start
	;;
	status)
		status;
	;;
	*)
		echo $"Use: {start|stop|restart|status}" 
		exit 2
esac
exit 0;