-- MySQL Script generated by MySQL Workbench
-- 05/19/15 12:30:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema prints
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema prints
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prints` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `prints` ;

-- -----------------------------------------------------
-- Table `prints`.`printers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prints`.`printers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `local` VARCHAR(455) NULL,
  `descrition` TEXT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prints`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prints`.`groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `quota` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prints`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prints`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `group_id` INT NULL,
  `quota` INT NULL DEFAULT 0,
  `status` TINYINT(1) NULL DEFAULT 1,
  `job_count` INT NULL DEFAULT 0,
  `print_count` INT NULL DEFAULT 0,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_users_groups1_idx` (`group_id` ASC),
  CONSTRAINT `fk_users_groups1`
    FOREIGN KEY (`group_id`)
    REFERENCES `prints`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prints`.`jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prints`.`jobs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `printer_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `pages` INT NOT NULL,
  `copies` INT NULL,
  `host` VARCHAR(255) NULL,
  `file` VARCHAR(255) NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_jobs_users_idx` (`user_id` ASC),
  INDEX `fk_jobs_prints1_idx` (`printer_id` ASC),
  CONSTRAINT `fk_jobs_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `prints`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_jobs_prints1`
    FOREIGN KEY (`printer_id`)
    REFERENCES `prints`.`printers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prints`.`users_printers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prints`.`users_printers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `printer_id` INT NOT NULL,
  INDEX `fk_users_has_printers_printers1_idx` (`printer_id` ASC),
  INDEX `fk_users_has_printers_users1_idx` (`user_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_users_has_printers_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `prints`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_printers_printers1`
    FOREIGN KEY (`printer_id`)
    REFERENCES `prints`.`printers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prints`.`archives`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prints`.`archives` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `size` VARCHAR(45) NULL,
  `file` VARCHAR(255) NULL,
  `file_dir` VARCHAR(255) NOT NULL,
  `permission` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_files_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_files_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `prints`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
